### ISSUE TITLE
13:25:00,411 |-WARN in net.logstash.logback.appender.LogstashTcpSocketAppender[logstash] - Log destination localhost/<unresolved>:5000: connection failed. java.net.ConnectException: Connection refused: no further information

### ISSUE THREAD

**Issue by javaHelper** [SaiUpadhyayula/springboot-microservices-project#3]
I am getting the below error when executing product-service

```java
13:25:00,411 |-WARN in net.logstash.logback.appender.LogstashTcpSocketAppender[logstash] - Log destination localhost/<unresolved>:5000: connection failed. java.net.ConnectException: Connection refused: no further information
	at java.net.ConnectException: Connection refused: no further information
	at 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
	at 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
	at 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at 	at java.base/java.net.Socket.connect(Socket.java:648)
	at 	at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender$TcpSendingEventHandler.openSocket(AbstractLogstashTcpSocketAppender.java:718)
	at 	at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender$TcpSendingEventHandler.onStart(AbstractLogstashTcpSocketAppender.java:638)
	at 	at net.logstash.logback.appender.AsyncDisruptorAppender$EventClearingEventHandler.onStart(AsyncDisruptorAppender.java:351)
	at 	at net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.notifyStart(BatchEventProcessor.java:224)
	at 	at net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:120)
	at 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at 	at java.base/java.lang.Thread.run(Thread.java:832)
13:25:00,412 |-WARN in net.logstash.logback.appender.LogstashTcpSocketAppender[logstash] - Log destination localhost/<unresolved>:5000: Waiting 27991ms before attempting reconnection.
13:25:30,407 |-WARN in net.logstash.logback.appender.LogstashTcpSocketAppender[logstash] - Log destination localhost/<unresolved>:5000: connection failed. java.net.ConnectException: Connection refused: no further information
	at java.net.ConnectException: Connection refused: no further information
	at 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
	at 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
	at 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at 	at java.base/java.net.Socket.connect(Socket.java:648)
	at 	at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender$TcpSendingEventHandler.openSocket(AbstractLogstashTcpSocketAppender.java:718)
	at 	at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender$TcpSendingEventHandler.onStart(AbstractLogstashTcpSocketAppender.java:638)
	at 	at net.logstash.logback.appender.AsyncDisruptorAppender$EventClearingEventHandler.onStart(AsyncDisruptorAppender.java:351)
	at 	at net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.notifyStart(BatchEventProcessor.java:224)
	at 	at net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:120)
	at 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at 	at java.base/java.lang.Thread.run(Thread.java:832)
13:25:30,408 |-WARN in net.logstash.logback.appender.LogstashTcpSocketAppender[logstash] - Log destination localhost/<unresolved>:5000: Waiting 27996ms before attempting reconnection.
13:26:00,443 |-WARN in net.logstash.logback.appender.LogstashTcpSocketAppender[logstash] - Log destination localhost/<unresolved>:5000: connection failed. java.net.ConnectException: Connection refused: no further information
	at java.net.ConnectException: Connection refused: no further information
	at 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
	at 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
	at 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at 	at java.base/java.net.Socket.connect(Socket.java:648)
	at 	at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender$TcpSendingEventHandler.openSocket(AbstractLogstashTcpSocketAppender.java:718)
	at 	at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender$TcpSendingEventHandler.onStart(AbstractLogstashTcpSocketAppender.java:638)
	at 	at net.logstash.logback.appender.AsyncDisruptorAppender$EventClearingEventHandler.onStart(AsyncDisruptorAppender.java:351)
	at 	at net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.notifyStart(BatchEventProcessor.java:224)
	at 	at net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:120)
	at 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at 	at java.base/java.lang.Thread.run(Thread.java:832)
[2m2021-05-13 13:29:06.722[0;39m [32m INFO[0;39m [35m7744[0;39m [2m---[0;39m [2m[trap-executor-0][0;39m [36mc.n.d.s.r.aws.ConfigClusterResolver     [0;39m [2m:[0;39m Resolving eureka endpoints via configuration

```

**Comment by jpmottin** [comment]
Hi @javaHelper, have you started Logstash (from ELK stack) with this config in **logstash.conf** file ? 

```
input {
	beats {
		port => 5044
	}

	tcp {
		port => 5000
		codec => json
	}
}
```

Here, you can see the configuration for Logstash to listen on this specific port 5000.

**Comment by SaiUpadhyayula** [comment]
@javaHelper Are you still facing this error ?

**Comment by javaHelper** [comment]
Sorry I had not done the ELK setup, I did that now, but still the POST request not working at my side with the latest code.

logs

```java
[2m2021-06-02 11:50:05.253[0;39m [32m INFO [order-service,,][0;39m [35m3396[0;39m [2m---[0;39m [2m[           main][0;39m [36mcom.netflix.discovery.DiscoveryClient   [0;39m [2m:[0;39m Discovery Client initialized at timestamp 1622614805251 with initial instances count: 3
[2m2021-06-02 11:50:05.268[0;39m [32m INFO [order-service,,][0;39m [35m3396[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.s.c.n.e.s.EurekaServiceRegistry       [0;39m [2m:[0;39m Registering application ORDER-SERVICE with eureka with status UP
[2m2021-06-02 11:50:05.269[0;39m [32m INFO [order-service,,][0;39m [35m3396[0;39m [2m---[0;39m [2m[           main][0;39m [36mcom.netflix.discovery.DiscoveryClient   [0;39m [2m:[0;39m Saw local status change event StatusChangeEvent [timestamp=1622614805269, current=UP, previous=STARTING]
[2m2021-06-02 11:50:05.272[0;39m [32m INFO [order-service,,][0;39m [35m3396[0;39m [2m---[0;39m [2m[nfoReplicator-0][0;39m [36mcom.netflix.discovery.DiscoveryClient   [0;39m [2m:[0;39m DiscoveryClient_ORDER-SERVICE/order-service:95348804-a182-4903-aee6-73832bc95fe3: registering service...
[2m2021-06-02 11:50:05.350[0;39m [32m INFO [order-service,,][0;39m [35m3396[0;39m [2m---[0;39m [2m[nfoReplicator-0][0;39m [36mcom.netflix.discovery.DiscoveryClient   [0;39m [2m:[0;39m DiscoveryClient_ORDER-SERVICE/order-service:95348804-a182-4903-aee6-73832bc95fe3 - registration status: 204
[2m2021-06-02 11:50:06.632[0;39m [32m INFO [order-service,,][0;39m [35m3396[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.s.cloud.commons.util.InetUtils        [0;39m [2m:[0;39m Cannot determine local hostname
[2m2021-06-02 11:50:06.702[0;39m [32m INFO [order-service,,][0;39m [35m3396[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.s.i.monitor.IntegrationMBeanExporter  [0;39m [2m:[0;39m Registering MessageChannel springCloudBus.anonymous.9mE0oRrPR7OdyRJyA08MQQ.errors
[2m2021-06-02 11:50:06.848[0;39m [32m INFO [order-service,,][0;39m [35m3396[0;39m [2m---[0;39m [2m[           main][0;39m [36mc.p.t.o.OrderServiceApplication         [0;39m [2m:[0;39m Started OrderServiceApplication in 48.271 seconds (JVM running for 52.017)
[2m2021-06-02 11:55:05.075[0;39m [32m INFO [order-service,,][0;39m [35m3396[0;39m [2m---[0;39m [2m[trap-executor-0][0;39m [36mc.n.d.s.r.aws.ConfigClusterResolver     [0;39m [2m:[0;39m Resolving eureka endpoints via configuration
[2m2021-06-02 12:00:05.077[0;39m [32m INFO [order-service,,][0;39m [35m3396[0;39m [2m---[0;39m [2m[trap-executor-0][0;39m [36mc.n.d.s.r.aws.ConfigClusterResolver     [0;39m [2m:[0;39m Resolving eureka endpoints via configuration
[2m2021-06-02 12:05:05.081[0;39m [32m INFO [order-service,,][0;39m [35m3396[0;39m [2m---[0;39m [2m[trap-executor-0][0;39m [36mc.n.d.s.r.aws.ConfigClusterResolver     [0;39m [2m:[0;39m Resolving eureka endpoints via configuration
[2m2021-06-02 12:10:05.082[0;39m [32m INFO [order-service,,][0;39m [35m3396[0;39m [2m---[0;39m [2m[trap-executor-0][0;39m [36mc.n.d.s.r.aws.ConfigClusterResolver     [0;39m [2m:[0;39m Resolving eureka endpoints via configuration
[2m2021-06-02 12:15:05.086[0;39m [32m INFO [order-service,,][0;39m [35m3396[0;39m [2m---[0;39m [2m[trap-executor-0][0;39m [36mc.n.d.s.r.aws.ConfigClusterResolver     [0;39m [2m:[0;39m Resolving eureka endpoints via configuration
[2m2021-06-02 12:20:05.089[0;39m [32m INFO [order-service,,][0;39m [35m3396[0;39m [2m---[0;39m [2m[trap-executor-0][0;39m [36mc.n.d.s.r.aws.ConfigClusterResolver     [0;39m [2m:[0;39m Resolving eureka endpoints via configuration
[2m2021-06-02 12:25:05.092[0;39m [32m INFO [order-service,,][0;39m [35m3396[0;39m [2m---[0;39m [2m[trap-executor-0][0;39m [36mc.n.d.s.r.aws.ConfigClusterResolver     [0;39m [2m:[0;39m Resolving eureka endpoints via configuration
[2m2021-06-02 12:30:05.096[0;39m [32m INFO [order-service,,][0;39m [35m3396[0;39m [2m---[0;39m [2m[trap-executor-0][0;39m [36mc.n.d.s.r.aws.ConfigClusterResolver     [0;39m [2m:[0;39m Resolving eureka endpoints via configuration
```

Postman

![image](https://user-images.githubusercontent.com/54174687/120442835-ad544a00-c3a3-11eb-81fa-f0b631cccbcd.png)

**Comment by SaiUpadhyayula** [comment]
@javaHelper  Can you cross-check if you are not sending the SessionID twice as part of the POST Request?

**Comment by SaiUpadhyayula** [comment]
Solution for the above problem is already addressed in the issue - https://github.com/SaiUpadhyayula/springboot-microservices-project/issues/4
